resource "jamfpro_api_role" "jamf-trust-security-cloud-uem-connect" {
  display_name = "Jamf Trust (Security Cloud) - UEM Connect"
  privileges   = [
    "Create API Roles",
    "Create Computer Extension Attributes",
    "Create iOS Configuration Profiles",
    "Create macOS Configuration Profiles",
    "Create Mobile Device Extension Attributes",
    "Delete Computer Extension Attributes",
    "Delete Mobile Device Extension Attributes",
    "Read API Roles",
    "Read Computer Extension Attributes",
    "Read Computers",
    "Read iOS Configuration Profiles",
    "Read Mac Applications",
    "Read macOS Configuration Profiles",
    "Read Mobile Device Applications",
    "Read Mobile Device Extension Attributes",
    "Read Mobile Devices",
    "Read Smart Computer Groups",
    "Read Smart Mobile Device Groups",
    "Read Static Computer Groups",
    "Read Static Mobile Device Groups",
    "Update API Roles",
    "Update Computer Extension Attributes",
    "Update Computers",
    "Update iOS Configuration Profiles",
    "Update macOS Configuration Profiles",
    "Update Mobile Device Extension Attributes",
    "Update Mobile Devices",
    "Update Smart Computer Groups",
    "Update Smart Mobile Device Groups",
    "Update Static Computer Groups",
    "Update Static Mobile Device Groups",
    "Update User",
  ]
}
